Repository jupyter-server/enterprise_gateway, pull requests merged in 2022-04, with the labels that each got.

#1067 Clean up pytest handling
  .github/workflows/build.yml
  Makefile
  enterprise_gateway/enterprisegatewayapp.py
  enterprise_gateway/tests/test_handlers.py
  pyproject.toml
  setup.py
Labels: maintenance

#1068 Add a kernel opening mechanism for load balancing!
  enterprise_gateway/mixins.py
  enterprise_gateway/services/kernels/remotemanager.py
  enterprise_gateway/services/processproxies/distributed.py
Labels: enhancement, resource management, network, kernels

#1072 Update links to default branch
  README.md
  docs/source/contributors/devinstall.md
  docs/source/contributors/docker.md
  docs/source/contributors/system-architecture.md
  docs/source/developers/custom-images.md
  docs/source/developers/kernel-launcher.md
  docs/source/developers/kernel-specification.md
  docs/source/developers/rest-api.rst
  docs/source/operators/config-security.md
  docs/source/operators/deploy-docker.md
  docs/source/operators/deploy-kubernetes.md
  docs/source/other/troubleshooting.md
  etc/docker/enterprise-gateway/README.md
  etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
  website/platform-kubernetes.md
Labels: documentation

#1070 Add doc entry for load-balancing algorithm configuration
  docs/source/operators/config-cli.md
  docs/source/operators/deploy-distributed.md
  docs/source/users/kernel-envs.md
  enterprise_gateway/mixins.py
Labels: documentation

#1076 Support startup scripts and ipykernel subclasses
  docs/source/developers/kernel-launcher.md
  docs/source/developers/kernel-specification.md
  etc/kernel-launchers/python/scripts/launch_ipykernel.py
Labels: enhancement, python kernel (iPython)

#1079 Remove conda env config from build workflow
  .github/workflows/build.yml
  Makefile
  docs/Makefile
  docs/source/contributors/devinstall.md
  setup.py
Labels: maintenance
