Repository jupyter-server/enterprise_gateway, pull requests merged in 2022-06, with the labels that each got.

#1099 Add support to define terminationGracePeriodSeconds in helm chart
  docs/source/operators/deploy-kubernetes.md
  etc/kubernetes/helm/enterprise-gateway/templates/deployment.yaml
  etc/kubernetes/helm/enterprise-gateway/values.yaml
Labels: enhancement, kubernetes

#1102 Release preparation
  docs/source/operators/deploy-kubernetes.md
  release.sh
Labels: infrastructure & build, maintenance

#1106 Enabling specifying annotations for service accounts in helm chart
  etc/kubernetes/helm/enterprise-gateway/templates/eg-serviceaccount.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/kip-serviceaccount.yaml
  etc/kubernetes/helm/enterprise-gateway/values.yaml
Labels: kubernetes

#1090 Refactoring EG Kernel Image Puller (KIP) Python Script
  docs/source/operators/deploy-kubernetes.md
  etc/docker/kernel-image-puller/kernel_image_puller.py
  etc/kubernetes/helm/enterprise-gateway/templates/daemonset.yaml
  etc/kubernetes/helm/enterprise-gateway/values.yaml
Labels: kubernetes

#1101 Added new WebhookKernelSessionManager for Kernel Persistence
  docs/source/operators/config-cli.md
  docs/source/operators/config-kernel-persistence.md
  docs/source/operators/index.rst
  enterprise_gateway/enterprisegatewayapp.py
  enterprise_gateway/services/sessions/kernelsessionmanager.py
Labels: enhancement, performance & scalability

#1121 Make EnterpriseGatewayApp.shutdown more robust, since it's a cleanup procedure
  enterprise_gateway/enterprisegatewayapp.py
Labels: runtime

#1119 Enable EG to create pods via CRDs on Spark Operator
  etc/kubernetes/enterprise-gateway.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/eg-clusterrole.yaml
Labels: bug, security, kubernetes, Spark

#1117 Fix shutdown issues
  enterprise_gateway/services/processproxies/processproxy.py
  etc/kernel-launchers/python/scripts/launch_ipykernel.py
  etc/kernelspecs/spark_R_conductor_cluster/kernel.json
  etc/kernelspecs/spark_R_yarn_cluster/kernel.json
  etc/kernelspecs/spark_python_conductor_cluster/kernel.json
  etc/kernelspecs/spark_python_yarn_cluster/kernel.json
  etc/kernelspecs/spark_scala_conductor_cluster/kernel.json
  etc/kernelspecs/spark_scala_yarn_cluster/kernel.json
Labels: bug

#1095 Availability modes
  docs/source/operators/config-availability.md
  docs/source/operators/config-cli.md
  docs/source/operators/config-kernel-persistence.md
  docs/source/operators/config-security.md
  docs/source/operators/deploy-kubernetes.md
  docs/source/operators/index.rst
  enterprise_gateway/enterprisegatewayapp.py
  enterprise_gateway/mixins.py
  enterprise_gateway/services/kernels/remotemanager.py
  enterprise_gateway/tests/test_gatewayapp.py
Labels: enhancement, performance & scalability

#1122 Update tensorflow-gpu base image
  etc/docker/kernel-tf-gpu-py/Dockerfile
Labels: kubernetes, docker, maintenance

#1125 KIP: Define pulled_images as set, not list
  etc/docker/kernel-image-puller/kernel_image_puller.py
Labels: bug
