Repository jupyter-server/enterprise_gateway, pull requests merged in 2022-10, with the labels that each got.

#1164 Flow configured envs from client to kernel pod
  enterprise_gateway/services/processproxies/k8s.py
  etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2
  etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
Labels: bug, kubernetes

#1171 Maintenance cleanup
  .flake8
  .github/ISSUE_TEMPLATE.md
  .github/workflows/build.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  LICENSE.md
  README.md
  docs/source/contributors/system-architecture.md
  docs/source/developers/custom-images.md
  docs/source/developers/dev-process-proxy.md
  docs/source/developers/kernel-launcher.md
  docs/source/operators/config-cli.md
  docs/source/operators/config-dynamic.md
  docs/source/operators/config-security.md
  docs/source/operators/deploy-distributed.md
  docs/source/operators/deploy-docker.md
  docs/source/operators/deploy-kubernetes.md
  docs/source/operators/deploy-single.md
  docs/source/operators/deploy-yarn-cluster.md
  docs/source/other/troubleshooting.md
  enterprise_gateway/services/sessions/kernelsessionmanager.py
  pyproject.toml
  website/index.md
  website/platform-kubernetes.md
  website/platform-spark.md
  website/privacy-policy.md
Labels: maintenance

#1178 Fix helm version handling and package naming
  Makefile
  docs/source/operators/deploy-kubernetes.md
  etc/kubernetes/helm/enterprise-gateway/Chart.yaml
  release.sh
Labels: bug, infrastructure & build

#1180 Fix version portion of download command to refer to tag name
  docs/source/operators/deploy-kubernetes.md
Labels: bug, documentation

#1181 [feature] add support for manage service and configmap in kernel-pod
  etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
Labels: enhancement, kubernetes
