Repository jupyter-server/enterprise_gateway, pull requests merged in 2022-05, with the labels that each got.

#1083 Use flit build backend
  .flake8
  .github/workflows/build.yml
  MANIFEST.in
  Makefile
  etc/docker/enterprise-gateway-demo/Dockerfile
  pyproject.toml
  setup.py
Labels: maintenance

#1084 fix(k8s): handle status of deleted Pod correctly
  enterprise_gateway/services/processproxies/k8s.py
Labels: bug, kubernetes

#1091 Use hatch and tbump
  .github/workflows/build.yml
  pyproject.toml
  release.sh
Labels: maintenance

#1073 update helm chart ingress
  Makefile
  docs/source/operators/deploy-kubernetes.md
  etc/kubernetes/enterprise-gateway.yaml
  etc/kubernetes/helm/enterprise-gateway/Chart.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/daemonset.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/deployment.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/eg-clusterrole.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/eg-clusterrolebinding.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/eg-serviceaccount.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/imagepullSecret.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/ingress.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/kip-clusterrole.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/kip-clusterrolebinding.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/kip-serviceaccount.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/psp.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/service.yaml
  etc/kubernetes/helm/enterprise-gateway/templates/serviceaccount.yaml
  etc/kubernetes/helm/enterprise-gateway/values.yaml
  pyproject.toml
  release.sh
Labels: kubernetes, configuration

#1092 Bump paramiko version, remove temp ignore of deprecation warning
  pyproject.toml
Labels: maintenance

#1093 Enable CodeQL analysis in CI
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
  enterprise_gateway/client/gateway_client.py
  enterprise_gateway/services/processproxies/distributed.py
  enterprise_gateway/services/processproxies/processproxy.py
  enterprise_gateway/services/processproxies/yarn.py
  etc/kernel-launchers/R/scripts/server_listener.py
  etc/kernel-launchers/docker/scripts/launch_docker.py
  etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
  etc/kernel-launchers/operators/scripts/launch_custom_resource.py
  etc/kernel-launchers/python/scripts/launch_ipykernel.py
Labels: maintenance
