Repository jupyter-server/enterprise_gateway, pull requests merged in 2022-07, with the labels that each got.

#1126 Switch default to create PSP in KIP to false due to deprecation
  etc/kubernetes/helm/enterprise-gateway/values.yaml
Labels: configuration

#1115 Changes for handling interrupts for PySpark Kubernetes Kernel
  etc/kernel-launchers/python/scripts/launch_ipykernel.py
Labels: enhancement, python kernel (iPython), Spark

#1130 Add type hints to EG application
  enterprise_gateway/base/handlers.py
  enterprise_gateway/enterprisegatewayapp.py
  enterprise_gateway/mixins.py
  enterprise_gateway/services/api/handlers.py
  enterprise_gateway/services/kernels/handlers.py
  enterprise_gateway/services/sessions/handlers.py
Labels: infrastructure & build

#1132 Add kernel launch sequence diagram to contributors guide
  docs/doc-requirements.txt
  docs/source/_static/custom.css
  docs/source/conf.py
  docs/source/contributors/index.rst
  docs/source/contributors/sequence-diagrams.md
Labels: documentation

#1139 Enable overriding Helm location from env var
  Makefile
Labels: infrastructure & build, kubernetes
