Repository jupyter-server/enterprise_gateway, pull requests merged in 2022-03, with the labels that each got.

#1044 Fix build to propagate SA macro between makefiles
  etc/Makefile
Labels: Bug, Infrastructure & Build

#1043 Fix operator references that were directing to Python docs
  docs/source/index.rst
  docs/source/users/index.rst
Labels: Bug, Documentation

#1046 Remove usage of ipython_genutils
  enterprise_gateway/services/kernels/remotemanager.py
  enterprise_gateway/services/processproxies/processproxy.py
  enterprise_gateway/services/sessions/kernelsessionmanager.py
  enterprise_gateway/services/sessions/sessionmanager.py
  enterprise_gateway/tests/test_enterprise_gateway.py
Labels: Bug
