Repository jupyter-server/enterprise_gateway, pull requests merged in 2023-01, with the labels that each got.

#1230 Start EG in demo-image to inherit PYSPARK_PYTHON env
  etc/docker/enterprise-gateway-demo/start-enterprise-gateway.sh.template
Labels: infrastructure & build

#1239 Update python interrupt test
  enterprise_gateway/itests/test_python_kernel.py
Labels: bug, testing

#1242 Flow envs to spark operator pods
  docs/source/operators/deploy-kubernetes.md
  etc/kernel-launchers/operators/scripts/launch_custom_resource.py
  etc/kernel-launchers/operators/scripts/sparkoperator.k8s.io-v1beta2.yaml.j2
Labels: kubernetes, Spark

#1240 Disable healthcheck on kernel-images derived from notebook images
  etc/docker/kernel-py/Dockerfile
  etc/docker/kernel-r/Dockerfile
  etc/docker/kernel-tf-py/Dockerfile
Labels: configuration, docker

#1245 Add more linting
  .pre-commit-config.yaml
  enterprise_gateway/client/gateway_client.py
  enterprise_gateway/enterprisegatewayapp.py
  enterprise_gateway/itests/test_python_kernel.py
  enterprise_gateway/itests/test_r_kernel.py
  enterprise_gateway/itests/test_scala_kernel.py
  enterprise_gateway/mixins.py
  enterprise_gateway/services/kernels/handlers.py
  enterprise_gateway/services/kernels/remotemanager.py
  enterprise_gateway/services/kernelspecs/kernelspec_cache.py
  enterprise_gateway/services/processproxies/conductor.py
  enterprise_gateway/services/processproxies/container.py
  enterprise_gateway/services/processproxies/distributed.py
  enterprise_gateway/services/processproxies/docker_swarm.py
  enterprise_gateway/services/processproxies/k8s.py
  enterprise_gateway/services/processproxies/processproxy.py
  enterprise_gateway/services/sessions/kernelsessionmanager.py
  enterprise_gateway/services/sessions/sessionmanager.py
  etc/docker/kernel-image-puller/kernel_image_puller.py
  etc/kernel-launchers/R/scripts/server_listener.py
  etc/kernel-launchers/docker/scripts/launch_docker.py
  etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
  etc/kernel-launchers/operators/scripts/launch_custom_resource.py
  etc/kernel-launchers/python/scripts/launch_ipykernel.py
  pyproject.toml
Labels: maintenance
